version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            rsync -e "ssh -o StrictHostKeyChecking=no" -avzn $CIRCLE_WORKING_DIRECTORY $PROD_SERVER:$PATH_TO_WORDPRESS_DIRECTORY_ONSERVER

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master